### ISSUE TITLE
弹幕在某些情况下会出现重叠

### ISSUE THREAD

**Issue by hugeorange** [zerosoul/rc-bullets#10]
如题：没找到触发重叠的条件
![image](https://user-images.githubusercontent.com/18440746/73631627-847b5200-4694-11ea-8f24-e5b6badae878.png)

**Comment by zerosoul** [comment]
> 如题：没找到触发重叠的条件
> ![image](https://user-images.githubusercontent.com/18440746/73631627-847b5200-4694-11ea-8f24-e5b6badae878.png)

嗯 严格来说这个应该不是重叠了，是弹幕出的速度不一致造成的。
我的弹幕滚动的算法参考的这篇文章：https://juejin.im/entry/5b56c567e51d45198a2ee509

感谢反馈，我想办法优化下这块：
1. 优先使用**空弹道**
2. 弹幕速度固定
