### ISSUE TITLE
在某些安卓手机上，弹起虚拟键盘会导致触发页面resize，然后继而页面弹幕出现堆叠

### ISSUE THREAD

**Issue by hugeorange** [zerosoul/rc-bullets#11]
如题：

在某些安卓手机上（如魅族），弹起虚拟键盘再收回，弹幕出现堆叠 

https://github.com/zerosoul/rc-bullets/blob/1052d1430d42c3f039d2e12df94afdccef2fe788/src/helper.js#L17

我把这段 resize代码去掉就好了，，，不知这段代码是出于什么考虑 ？
![image](https://user-images.githubusercontent.com/18440746/73938435-37141480-4922-11ea-8b62-dd88c60921ef.png)

**Comment by zerosoul** [comment]
> 如题：
> 
> 在某些安卓手机上（如魅族），弹起虚拟键盘再收回，弹幕出现堆叠
> 
> https://github.com/zerosoul/rc-bullets/blob/1052d1430d42c3f039d2e12df94afdccef2fe788/src/helper.js#L17
> 
> 我把这段 resize代码去掉就好了，，，不知这段代码是出于什么考虑 ？
> ![image](https://user-images.githubusercontent.com/18440746/73938435-37141480-4922-11ea-8b62-dd88c60921ef.png)

当时只考虑PC端的窗口变动了，不过这块作用有些鸡肋，已在最新版本去掉了。
