### ISSUE TITLE
关于支持vue

### ISSUE THREAD

**Issue by GuoGuang** [zerosoul/rc-bullets#2]
是否考虑扩展vue组件，目前国内一般用vue的相对较多，个人项目尤甚，如果可以扩展支持vue，我想使用的人会等多。

**Comment by zerosoul** [comment]
道理没错，非常感谢反馈。
可是你这样说，总感觉像是去麦当劳要一份KFC吮指原味鸡🤣。
这个是服务react生态的类库，暂不考虑vue哈。
