### ISSUE TITLE
防止重叠

### ISSUE THREAD

**Issue by blueYufisher** [zerosoul/rc-bullets#4]
大神超级厉害的，效果超好，不过想问问如何防止多个弹幕重叠呢？

**Comment by zerosoul** [comment]
> 大神超级厉害的，效果超好，不过想问问如何防止多个弹幕重叠呢？

额 当时解决弹幕垂直方向重叠主要是参考这篇文章：https://juejin.im/post/5b5a96fff265da0f8a14a8f9 做了一些改进，利用 `IntersectionObserver`机制，较优雅地解决了横向重叠问题。

这是核心思路，具体请看源码：`src/BulletScreen.js`。
