### ISSUE TITLE
可以一开始就让一部分弹幕出现在屏幕上吗

### ISSUE THREAD

**Issue by jesse-tang-93** [zerosoul/rc-bullets#6]

**Comment by zerosoul** [comment]
> _No description provided._

这个需求以目前的API完全可以模拟出来的，初始化后立即push几条弹幕，妥了。

**Comment by jesse-tang-93** [comment]
是想让弹幕出现在屏幕中央。并在页面打开后开始动画。后面循环的时候再从左到右。

**Comment by zerosoul** [comment]
> 是想让弹幕出现在屏幕中央。并在页面打开后开始动画。后面循环的时候再从左到右。

哦，这个需求有点偏离弹幕本身的功能属性了。其实也可以独立弹幕类库之外模拟的，先写好弹幕组件，用绝对定位先放上去，过一定时间，再让其他弹幕入场...

**Comment by jesse-tang-93** [comment]
是个思路哈哈。醍醐灌顶~
