### ISSUE TITLE
你好，可以关闭控制台的打印吗

### ISSUE THREAD

**Issue by jesse-tang-93** [zerosoul/rc-bullets#7]

**Comment by zerosoul** [comment]
> _No description provided._

Sure，是在使用我这个包的时候，有很多控制台打印吗？看了下代码，确实打包设置有问题，条件整反了。

**Comment by zerosoul** [comment]
> > _No description provided._
> 
> Sure，是在使用我这个包的时候，有很多控制台打印吗？看了下代码，确实打包设置有问题，条件整反了。

已在 最新版本 更正

**Comment by jesse-tang-93** [comment]
![image](https://user-images.githubusercontent.com/26913463/72657449-7e704a80-39df-11ea-91f3-70f19549a2bb.png)
你好，还是有打印。请看一下。

**Comment by zerosoul** [comment]
> ![image](https://user-images.githubusercontent.com/26913463/72657449-7e704a80-39df-11ea-91f3-70f19549a2bb.png)
> 你好，还是有打印。请看一下。

嗯 确实还有  漏掉了一处设置 已修复 @ 1.5.7
